### ISSUE TITLE
Clear InputFilter

### ISSUE THREAD

**Issue by benfoley** [jdlehman/react-fuzzy-filter#11]
Hi

Is there a method to clear the input field and reset the results? I've tried adding a ref on a container div and setting the value of the div's input to be empty, but this doesn't reset the data in filter results. 

thanks
Ben

**Comment by jdlehman** [comment]
Hmm, that is an interesting use case, currently that isn't supported other than through the user actually trigger the `onchange` events (https://github.com/jdlehman/react-fuzzy-filter/blob/master/src/InputFilter.js#L69).

This actually feels like a valuable addition to me. I am thinking that the `fuzzyFilterFactory` could export a change function that can be used to trigger changes outside the context of the user's interaction. For example, clicking a button to reset the search or something of that nature.

something like:
```js
const {InputFilter, FilterResults, changeInputValue} = fuzzyFilterFactory();
```
lemme see what I can throw together to support this use case

**Comment by jdlehman** [comment]
I have put together a PR (https://github.com/jdlehman/react-fuzzy-filter/pull/12) that should address this issue and will probably merge and release a new version in the next day or two. Let me know if this will work for your use case

**Comment by benfoley** [comment]
Thanks, I’ll check it out tonight!
