### ISSUE TITLE
Link or NavLink not working inside renderItem

### ISSUE THREAD

**Issue by hynese** [jdlehman/react-fuzzy-filter#2]
Hello, I have the following function:

```
import {NavLink} from 'react-router-dom'
...
import fuzzyFilterFactory from 'react-fuzzy-filter'
const {InputFilter, FilterResults} = fuzzyFilterFactory()

...
renderItem(job,rank) {

    //console.log("renderItem...");

    var self=this;

   


    var to='/jobs/'+job.id;
    
    return (
      <div key={rank}>
        <NavLink to={to}>{job.title}</NavLink>
        <div className="pull-right _right">
          <i>
        Added: {job.date_created_ago}
        <br/>
        Last updated: {job.date_modified_ago}
          </i>
        </div>
      </div>
    )
```

When I click NavLink, localhost/job/1234 doesn't work ;(

But if I go to the link from another page, it seems to work fine?

**Comment by jdlehman** [comment]
This library only handles rendering the matching subset of items. If the item is showing up, then it seems to be working correctly.

You mentioned `localhost/job/1234` does not work, but it looks like your code is going to `/jobs/1234` (unless that is a typo)

**Comment by hynese** [comment]
Hello, your code works perfectly. Thank you very much.

My problem was that the jobID was being passed in module constructor.

I needed to keep track of the jobID from the url and not rely on jobID as set in constructor.

**Comment by jdlehman** [comment]
Awesome, glad you figured it out!
