### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by ryanlewis** [jdlehman/react-fuzzy-filter#8]
This looks great for what we are after, good job!

I've just noticed that you are running an older version of RXJS, just wondering if you are still maintaining this project?

**Comment by jdlehman** [comment]
Yep! The feature set is fairly stable, but I definitely need to get better about keeping dependencies up to date.

Thanks for the reminder, I will take some time to get a new version through with updated dependencies, later tonight or early tomorrow! And PRs for any other issues or features are always welcome too 😄
